# This rule is not used by the project s3-mon itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over s3mon.dasmlab.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s3-mon
    app.kubernetes.io/managed-by: kustomize
  name: s3endpoint-admin-role
rules:
- apiGroups:
  - s3mon.dasmlab.org
  resources:
  - s3endpoints
  verbs:
  - '*'
- apiGroups:
  - s3mon.dasmlab.org
  resources:
  - s3endpoints/status
  verbs:
  - get
