#!/usr/bin/env bash
# Wrap deploy/grafana/s3-mon-dashboard.json in the ConfigMap the MCO grafana-dashboard-loader picks up.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

JSON="deploy/grafana/s3-mon-dashboard.json"
OUT="deploy/grafana/s3-mon-dashboard-configmap.yaml"
FOLDER="${FOLDER:-S3}"

{
  cat <<EOF
# GENERATED by hack/render-grafana-configmap.sh — do not edit; edit ${JSON}.
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-mon-dashboard
  namespace: open-cluster-management-observability
  labels:
    grafana-custom-dashboard: "true"
  annotations:
    observability.open-cluster-management.io/dashboard-folder: ${FOLDER}
data:
  s3-mon-dashboard.json: |-
EOF
  sed 's/^/    /' "${JSON}"
} > "${OUT}"

echo "rendered ${OUT} (folder ${FOLDER})"
