#!/usr/bin/env bash
# Render deploy/acm/policy-hub-s3-mon.yaml from its template, embedding the generated CRD and
# the Grafana dashboard, and pinning the image to VERSION (default: v$(cat .localbuild)).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

VERSION="${VERSION:-v$(tr -d '[:space:]' < .localbuild)}"
IMAGE="${IMAGE:-ghcr.io/dasmlab/s3-mon:${VERSION}}"
TMPL="deploy/acm/policy-hub-s3-mon.tmpl.yaml"
CRD="config/crd/bases/s3mon.dasmlab.org_s3endpoints.yaml"
DASHBOARD="deploy/grafana/s3-mon-dashboard.json"
OUT="deploy/acm/policy-hub-s3-mon.yaml"

{
  echo "# GENERATED by hack/render-acm-policy.sh — do not edit; edit ${TMPL}."
  while IFS= read -r line; do
    if [[ "${line}" == "__CRD__" ]]; then
      grep -v '^---$' "${CRD}" | sed 's/^/                /'
    elif [[ "${line}" == "__DASHBOARD__" ]]; then
      sed 's/^/                    /' "${DASHBOARD}"
    else
      printf '%s\n' "${line//__IMAGE__/${IMAGE}}"
    fi
  done < "${TMPL}"
} > "${OUT}"

echo "rendered ${OUT} (image ${IMAGE})"
